# Generated by Django 5.2.5 on 2025-08-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_userprofile_date_of_birth_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
