# Generated by Django 5.2.5 on 2025-08-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', help_text='Priority level: High, Medium or Low', max_length=1),
        ),
    ]
