# Generated by Django 5.2.5 on 2025-08-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_task_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
    ]
