# Generated by Django 5.2.5 on 2025-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_task_recurrence_alter_task_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', help_text='Priority level: High, Medium or Low', max_length=1),
        ),
    ]
